{% set version = '1.23' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-desolve
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/deSolve_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/deSolve/deSolve_{{ version }}.tar.gz
  sha256: 8f19bb978045cfa9eb7be344d55c2be9fc5722823b777f814519f407be0a6173

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('deSolve')"           # [not win]
    - "\"%R%\" -e \"library('deSolve')\""  # [win]

about:
  home: http://desolve.r-forge.r-project.org/
  license: GPL (>= 2)
  summary: Functions that solve initial value problems of a system of first-order ordinary differential
    equations ('ODE'), of partial differential equations ('PDE'), of differential algebraic
    equations ('DAE'), and of delay differential equations.  The functions provide an
    interface to the FORTRAN functions 'lsoda', 'lsodar', 'lsode', 'lsodes' of the 'ODEPACK'
    collection, to the FORTRAN functions 'dvode', 'zvode' and 'daspk' and a C-implementation
    of solvers of the 'Runge-Kutta' family with fixed or variable time steps.  The package
    contains routines designed for solving 'ODEs' resulting from 1-D, 2-D and 3-D partial
    differential equations ('PDE') that have been converted to 'ODEs' by numerical differencing.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - conda-forge/r

# Package: deSolve
# Version: 1.23
# Title: Solvers for Initial Value Problems of Differential Equations ('ODE', 'DAE', 'DDE')
# Authors@R: c(person("Karline","Soetaert", role = c("aut"),  email = "karline.soetaert@nioz.nl"), person("Thomas","Petzoldt", role = c("aut", "cre"), email = "thomas.petzoldt@tu-dresden.de"), person("R. Woodrow","Setzer", role = c("aut"), email = "setzer.woodrow@epa.gov"), person("odepack authors", role = "cph"))
# Author: Karline Soetaert [aut], Thomas Petzoldt [aut, cre], R. Woodrow Setzer [aut], odepack authors [cph]
# Maintainer: Thomas Petzoldt <thomas.petzoldt@tu-dresden.de>
# Depends: R (>= 2.15.0)
# Imports: methods, graphics, grDevices, stats
# Suggests: scatterplot3d, FME
# Description: Functions that solve initial value problems of a system of first-order ordinary differential equations ('ODE'), of partial differential equations ('PDE'), of differential algebraic equations ('DAE'), and of delay differential equations.  The functions provide an interface to the FORTRAN functions 'lsoda', 'lsodar', 'lsode', 'lsodes' of the 'ODEPACK' collection, to the FORTRAN functions 'dvode', 'zvode' and 'daspk' and a C-implementation of solvers of the 'Runge-Kutta' family with fixed or variable time steps.  The package contains routines designed for solving 'ODEs' resulting from 1-D, 2-D and 3-D partial differential equations ('PDE') that have been converted to 'ODEs' by numerical differencing.
# License: GPL (>= 2)
# URL: http://desolve.r-forge.r-project.org/
# LazyData: yes
# NeedsCompilation: yes
# Packaged: 2019-06-29 16:35:20 UTC; thpe
# Repository: CRAN
# Date/Publication: 2019-06-29 21:20:03 UTC
