travis:
  secure:
    BINSTAR_TOKEN: UOHMDZveHNn2X+KwbREBPeNlVIsHGrByq1V/XCbbUlq4NJbM4VAesEgQzKjVKbLpXri9vPvmXrpGsE5Vpc+VTwH1gNzFY/PVBxeooceYSmLyicB4wv2GDTPOiIoFFSR9x+M8zsiE9tOYAqG/BAx3Z+7l2tFf2gCv80G5h/srqKytIowqkzEqYkOH2pbtvzCRGwZAHH4hyWcjrsI4lzx0ktq3slPY/HWTFVsmK4VQwq0aW+1NlWBsjjoRdDn3JCvdtEcCyMbzGhnSPkviI/xN0sUsdw/v9t/O/3bhmupbGWYsJNySQTabxs8hZlHFH0N3LLaCuQVtuD9Y/MZ694oIy8K9mAdIzcG8daPxzPNyplq123AsUyM3F+M8MtTq0DV/I5Orjytu8WdjQ/06ES9uLE3zIUixPAqBNNsYQR3oeBRlbkwfqv0nZ2vlOTK2+3lab3NafbCGKXHpI/OSlD4oAqLE0LTZupHuG/WFGfC0wjY7MR6wBmVhKadW3dcm4s1HXNXgEbyr5hVP6If5B+lE30R1+UqTlBCpn/RSU50eHNwK+eMO2tPvkpJu1nw1QFxDKrQRDIGoQPSK5HiU+uKQf5yqMz3vK1wqAH/po/C33ayj0BQt5NEFTFG1HFcjvS3Wm9kl/8mzYYe6pwWDL88XZ/jjIqJnbyaUm+Mb7x/KPf8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
