travis:
  secure:
    BINSTAR_TOKEN: ZDxwyDgmzfbg5yWBfZVOXcf91GW81Hyakxb08p9lFMI0Ip54W0foCcLQggg5vB8y8EGBF7ZuiOK6wHKot6fPucuF0sFemrSkh72Cf4AAQWPWhfKkkLlBzMdoaNvpcBK/j+W9ZaPS/AWPZ3PcSmteYS072CX2NPk9hPWcI5z7DiDZyUdkWdqeEK4+EUQBpum1/1BRmzeP6Flxe2c7Ax+P3UF/DHvqVJTjbX9J2FFdpyYZe0yxh/3jg+pHNQirV5CU6/jUBBPImw3vu5W3Yrkjyv+J7aw0uHbJFmWR8ByQbF2HuQ8ET5cW6IREzZSMIwgisngBwvUIWiUK41eJ4Cr5GAdqrNNQyiZMWH9RC15epWc2/dl298PT8a6ZsHfpPeTh7NLudQM2PuAE3JpNLtujH12jd7tvYi3fr4ObbSNyWczdUY15v4T8j0WrZAVIT7vsJjDn+fVRbc6YxOaXxxiyU+AyasFYKT+kCQbp3WS3YEfcfvLnnZaaIJ3b5LR/5g/NMMMSrcmR8DONkAUj3jaFZZ90Jxy8+ftAopPMhqa2lpRq3R1gnaVvimwHAyHweotr+Zpn8rtRrtihgHD/Bg/4v8B3lJwgEuhEjl9soFk7EWpGnQhRQJnzGQ0lx26dA6/A0W+xAk4qaFQLg9PvAIynL7Wvfpcnmtyj1qwKu4jiU70=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
