travis:
  secure:
    BINSTAR_TOKEN: FeEwhCc8Ujd8zVeNvkGxNS6cExKJgYxzgFTtKu1Og0AuSLC5cwQyQnHYpwnxmhGdv9ag6iwcuTOWbyNusKb+yRrJi+FA9H516vjaZFNjgYrL5m0jomU1wHPS1yPSLR74cgn3X6ZKrgeD3Pejt7omgk+JQTH5sq8bUYK+XesCD+6PuRh6cAC/nGoZh4IfnrnjclLnC4fh9LKuEtTcBJzoB5yhxSeNetGF7RGrUxbAeqF1jhtwPDCV/KPqcneC/I8YXzhUXq6rLPSKkMv05Hj1xbAjytuzCJGG57r+BUJxhSKsiZvY98vqOdS4howV+gcnxSSAf9x3TCTpWjySAJzYt9WoMoRmpDrbNuQOy9OirIfK/22nSmJsHfFxbTZ3nhIoD0wVKMI5DkQKXoSmi2c8PRuJGzzl85YNMjCxhdIU2ybW6MBUXrHgmYqmVgnkuMlLOoo7G+/bg7sOfdJPmXqM7rowWbiRrlfEVjKOVGDTlxRvYhbrvtzFvCd8/jIHRZMmMVhlCiSnPiLcaxQtxk9ovV2WPjsEqvDLvdKqj/g14GpkvqL2DMK6gm1pU267YZdRlYfYmEHqVhnUYUtcAE87Mt4Lm8CwSnJvB4DHLTWGU3bj5us2BcYRsz3ZP88U9rlKi/SZuLTVJGLCFG2M/GmSeKdnA/69R5jTm+4TRImIOCk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
