travis:
  secure:
    BINSTAR_TOKEN: LEo33cX4FBW29tmqyIi2X1W+QbBUf24j+B1LNY3sJHkncqQjPqR2cggzVCnh3sByYdKaycqOu/lKvglnlWGw1DtNXzccnPmmX3BaznUXL8jiDhVHLc+izDjxjy8iH+4Ykt8Umi7s/bojFu46B7yfYT/QoCkEHemQamAM2sc5clmnNOkyJQd40s1E8uW9NjM3V8aVuzZIvqEEGh+9m+oZRvOy3DS8NbFG4I1+OVcyej/s4N/NDpGiOcO2XOSHE2NGVnl3sY2NWSw9WKjG9e+nWx+I+1/2m+RrXMYCvFCuIXPCUPbRBB5YDLVWJpC3ZBVzVRS4oR9XWqdKAoWrLIbwEE7FxF7NaxhsaW5MGOY9vFogTWzIwqfly29s2XNBhIiOFQ3bn01WblLB7THlLeMOL3obnOOYwXekxVTjqhMtfDlFs+lJQb3lH5fGK5zmYcLmQxTAImmAHL4B6sjoWG7fMrDP8Nm+SStZ6d2aD25kJq8wlSJWhz5fYu01ICSUiC7LzxdN4L4AcDpnk2r7D0u3x894TyS1s4ogKWqzwLdtWJ70EAywIInuZfn56fCm4xc2BKUXVHdOBV4P0PE1cwn9HcuU3luulZyh+iBYFbIH2PGSsKqbLrMK4CR65NO0Fqus5lmVvHh9cGOWW45FxjCs4rAsPo/trsx4fTzacQspgxM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
